
//CRUD DE USERS
GET http://localhost:5000/users

###

GET http://localhost:5000/users/1

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "username":"Juan1235",
    "name": "Juan25",
    "firstLN": "Perez5",
    "secondLN": "Perez5",
    "email": "a2011036725@ceti.mx",
    "phone": "33325154365",
    "pass": "122345",
    "role":  "employee"
}
###
PATCH  http://localhost:5000/users/10
Content-Type: application/json

{
    "username":"Juan1234",
    "name": "Juan24",
    "firstLN": "Perez4",
    "secondLN": "Perez4",
    "email": "a2011036724@ceti.mx",
    "phone": "33432515436",
    "pass": "122344",
    "role":  "employee"
}

###
DELETE http://localhost:5000/users/7

### 
//CRUD DE MACHINES
GET http://localhost:5000/machines
###
GET http://localhost:5000/machines/5
###
POST http://localhost:5000/machines
Content-Type: application/json

{
    "machineType": "lavadora",
    "model": "Ni tan Chingona 5000",
    "cicleTime": 45,
    "weight": 25,
    "status": "unavailable",
    "notes": "La compramos madreada"

}
###
PATCH http://localhost:5000/machines/6
Content-Type: application/json

{
    "machineType": "lavadora",
    "model": "Ni tan Chingona 5000",
    "cicleTime": 45,
    "weight": 25,
    "status": "available",
    "notes": "nomas aguanto 20"
}
###
DELETE http://localhost:5000/machines/6

###

//CRUD DE CATEGORIES
POST http://localhost:5000/categories
Content-Type: application/json

{
    "cateforyDes": "pruebas"
}

###

GET  http://localhost:5000/categories

###
GET  http://localhost:5000/categoriesId/2

###
GET  http://localhost:5000/categoriesName/pruebas

###
DELETE  http://localhost:5000/categories/5

###

DELETE  http://localhost:5000/categoriesName/pruebas

###



POST http://localhost:5000/services
Content-Type: application/json

{
    "description": "Lavado 8Kg",
    "price": 135.0,
    "time": 45,
    "weight": 8
}

###
GET http://localhost:5000/orders

###

GET http://localhost:5000/orders/1

###



