
//CRUD DE USERS
GET http://localhost:5000/users

###

GET http://localhost:5000/users/1

###

POST http://localhost:5000/sendMessage
Content-Type: application/json

{
  "id_order": 1,
  "name": "Israel",
  "email": "a20110367@ceti.mx",
  "tel": "5213313839768",
  "message": "IG de la minita es para probar el uso de las .env"
}

###

POST http://localhost:5000/auth
Content-Type: application/json

{
  "username":"isra",
  "pass":"1010"
}

###

POST http://localhost:5000/usersMany
Content-Type: application/json

###

POST http://localhost:5000/numberToWord
Content-Type: application/json

{
  "number": 117.15
}

###
POST http://localhost:5000/users
Content-Type: application/json

{
   
    "username": "Juan1234",
    "name": "Juan24",
    "firstLN": "Perez4",
    "secondLN": "Perez4",
    "email": "a2011036724@ceti.mx",
    "phone": "33432515436",
    "pass": "122344",
    "role": "employee"
}
###
PATCH  http://localhost:5000/users/6
Content-Type: application/json

{
    "username":"Juan123456",
    "name": "Juan2456",
    //"firstLN": "Perez4",
    //"secondLN": "Perez4",
    //"email": "a2011036724@ceti.mx",
    "phone": "334325154367",
    "pass": "122344",
    "role":  "employee"
}

###
DELETE http://localhost:5000/users/7

### 


//CRUD DE STAFF MEMBERS
GET http://localhost:5000/staffMembers

###

GET http://localhost:5000/staffMembers/2

###
POST http://localhost:5000/staffMembersMany
Content-Type: application/json

###
POST http://localhost:5000/staffMembers
Content-Type: application/json

{
    "name": "Juan24",
      "email": "a2011036724@ceti.mx",
      "phone": "33432515436",
      "firstLN": "Perez4",
      "id_Token": 222,
      "secondLN": "Perez4"
}

###
PATCH  http://localhost:5000/staffMembers/3
Content-Type: application/json

{
    "id_Token":333
    //"username":"Juan123456",
    //"name": "Juan2456",
    //"firstLN": "Perez4",
    //"secondLN": "Perez4",
    //"email": "a2011036724@ceti.mx",
    //"phone": "334325154367",
}

###
DELETE http://localhost:5000/staffMembers/7

### 



//CRUD DE CATEGORIES


POST http://localhost:5000/categoriesMany
Content-Type: application/json

[
  {
    "categoryDescription": "autoservicio"
  },
  {
    "categoryDescription": "encargo"
  },
  {
    "categoryDescription": "planchado"
  },
  {
    "categoryDescription": "pruebas"
  }
]

###
POST http://localhost:5000/categories
Content-Type: application/json

{
   "categoryDescription": "pruebas"
}

###

GET  http://localhost:5000/categories

###
GET  http://localhost:5000/categoriesId/2

###
GET  http://localhost:5000/categoriesName/pruebas

###
DELETE  http://localhost:5000/categoriesId/5

###

DELETE  http://localhost:5000/categoriesName/pruebas2

###

//CRUD DE Clientes
GET http://localhost:5000/clients

###

GET http://localhost:5000/clientsById/6

###
GET http://localhost:5000/clientsByEmail/uncorreo2@correo.com

###
GET http://localhost:5000/clientsByPhone/1234567733

###
POST http://localhost:5000/clientsMany
Content-Type: application/json


###
POST http://localhost:5000/clients
Content-Type: application/json

{
 "username": "Cliente3",
    "name": "Janito",
    "firstLN": "Lopez",
    "secondLN": "Perez",
    "email": "uncorreo2@correo.com",
    "phone": "1234567733",
    "pass": "1122334455"
}
###
PATCH  http://localhost:5000/clients/6
Content-Type: application/json

{
    "username":"JuanComplicado",
    "name": "Juan24",
    "firstLN": "Perez45",
    "secondLN": "Perez45",
    "email": "33333333335@ceti.mx",
    "phone": "55555555557",
    "pass": "1223445"
}

###
DELETE http://localhost:5000/clients/7

### 

//CRUD DE MACHINES
GET http://localhost:5000/machines
###
GET http://localhost:5000/machines/3
###
POST http://localhost:5000/Machines
Content-Type: application/json

{
    "machineType": "lavadora",
    "model": "Chingona 3000",
    "cicleTime": 45,
    "weight": 20,
    "status": "available",
    "notes": ""
}
###


POST http://localhost:5000/Machines
Content-Type: application/json

{
    "machineType": "secadora",
    "model": "Chingona 3000",
    "cicleTime": 45,
    "weight": 20,
    "status": "available",
    "notes": ""
}
###
POST http://localhost:5000/machinesMany
Content-Type: application/json


###
PATCH http://localhost:5000/machines/6
Content-Type: application/json

{
    "machineType": "lavadora",
    "model": "LG",
    "cicleTime": 35,
    "weight": 10,
    "status": "unavailable",
    "notes": "Se madreo"
}
###
DELETE http://localhost:5000/dryMachines/3
###

//CRUD DE MACHINES
GET http://localhost:5000/ironStations
###
GET http://localhost:5000/ironStations/5
###
POST http://localhost:5000/ironStation
Content-Type: application/json

{
    "status": "available",
    "notes": "estacion 1"
}
###
PATCH http://localhost:5000/ironStations/6
Content-Type: application/json

{
    "status": "available",
    "notes": "estacion 1"
}
###
DELETE http://localhost:5000/ironStations/6
###

//CRUD DE SERVICES

POST http://localhost:5000/services
Content-Type: application/json

{
    "description": "Lavado prueba 10 kg",
    "price": 90,
    "category_id": 2
}

###

POST http://localhost:5000/servicesLaundry
Content-Type: application/json

{
"description":"lavado 10 kilos encargo",
"price":100.00 ,
"category_id":2,
"washWeight":20,
"washCycleTime":45,
"dryWeight":20,
"dryCycleTime":60
}

###

POST http://localhost:5000/servicesSelfService
Content-Type: application/json

{
"description":"Lavado 20 kilos autoservicio",
"price":200.00 ,
"category_id":1,
"weight":20,
"cycleTime":45,
"machineType":"lavadora"
}

###

POST http://localhost:5000/servicesDrySelfService
Content-Type: application/json

{
  "description":"Secado 15 kilos autoservicio",
  "price":100.00 ,
  "dryWeight":10,
  "dryCycleTime":45
}

###

POST http://localhost:5000/servicesIron
Content-Type: application/json

{
"description":"Media Docena Planchado",
"price":30.00 ,
"pieces":6,
"cycleTime":45,
"category_id":3

}

###
GET  http://localhost:5000/services
###

GET http://localhost:5000/servicesLaundry
###


GET  http://localhost:5000/servicesById/1

###
PATCH  http://localhost:5000/services/8
Content-Type: application/json

{
    "description": "Lavado 25Kg",
    "category_id" : 3,
    "price": 250.0,
}
###

PATCH  http://localhost:5000/services/1
Content-Type: application/json

{
    "category_id": 1
}

###

PATCH  http://localhost:5000/servicesUpdateLaundry/43
Content-Type: application/json

{
"description":"lavado 10 kilos encargo",
"price":100.00 ,
"category_id":2,
"washWeight":20,
"washCycleTime":45,
"dryWeight":20,
"dryCycleTime":60
}

###

PATCH  http://localhost:5000/servicesUpdateWashSelfService/48
Content-Type: application/json

{
"description":"Lavado autoservicio 15 kilos",
"price":130.00 ,
"category_id":1,
"washWeight":10,
"washCycleTime":10
}

###


DELETE   http://localhost:5000/services/28

###

###
GET http://localhost:5000/servicesIronService

###


POST http://localhost:5000/servicesMany
Content-Type: application/json

###

PATCH  http://localhost:5000/services/31
Content-Type: application/json

{
    "description": "Lavado prueba 10 kg",
    "price": 150,
    "category_id": 2
}

###

DELETE   http://localhost:5000/services/31
Content-Type: application/json
###

///CRUD SERVICE ORDERS

POST http://localhost:5000/ordersLaundryService
Content-Type: application/json

{
  "serviceOrder":
  {
    "receptionDate": "2023-11-02T00:00:00.000Z",
    "orderStatus": "pending",
    "totalPrice": 300,
    "fk_client": 1,
    "created": "2023-11-03T04:46:52.708Z",
    "numberOfItems": 5,
    "payForm": "delivery",
    "payStatus": "paid",
    "receptionTime": "1970-01-01T00:00:00.000Z",
    "updatedAt": "2023-11-04T00:55:45.377Z",
    "fk_user": 3,
    "scheduledDeliveryDate": "2023-11-02T00:00:00.000Z",
    "scheduledDeliveryTime": null,
    "fk_categoryId": 1,
    "fk_deliveryDetail": null

  },
  "services":
      [ 
        {
          "fk_Service":1,
          "units":2,
          "subtotal":200
        },
        {
          "fk_Service":2,
          "units":2,
          "subtotal":200
        }
    ]
   
  
}

###
POST http://localhost:5000/ordersIronService
Content-Type: application/json

{
  "serviceOrder":
  {

    "receptionDate": "2023-11-02T00:00:00.000Z",
    "orderStatus": "pending",
    "totalPrice": 300,
    "fk_client": 1,
    "created": "2023-11-03T04:46:52.708Z",
    "numberOfItems": 5,
    "payForm": "delivery",
    "payStatus": "paid",
    "receptionTime": "1970-01-01T00:00:00.000Z",
    "updatedAt": "2023-11-04T00:55:45.377Z",
    "fk_user": 3,
    "scheduledDeliveryDate": "2023-11-02T00:00:00.000Z",
    "scheduledDeliveryTime": null,
    "fk_categoryId": 1,
    "fk_deliveryDetail": null
  },
  "services":
      [ 
        {
          "fk_Service":1,
          "units":1,
          "subtotal":60
        }
    ]
   
  
}
###

POST http://localhost:5000/ordersSelfService
Content-Type: application/json

{
  "serviceOrder":
  {
    "receptionDate": "2023-10-11T00:00:00.000Z",
    "orderStatus": "pending",
    "totalPrice": 600,
    "fk_client": 1,
    "created": "2023-11-03T04:46:52.708Z",
    "numberOfItems": 4,
    "payForm": "advance",
    "payStatus": "paid",
    "receptionTime": "1970-01-01T13:15:48.000Z",
    "updatedAt": "2023-11-04T00:55:45.377Z",
    "fk_user": 3,
    "scheduledDeliveryDate": "2023-11-02T00:00:00.000Z",
    "scheduledDeliveryTime": null,
    "fk_categoryId": 1
    
  },
 "services": 
  [
        {
          "units": 2,
          "subtotal": 200,
          "fk_Service": 1
        },
        {
          "units": 2,
          "subtotal": 400,
          "fk_Service": 2
        }
    ]
}
###


//CRUD DE ORDENES
GET http://localhost:5000/orders

###

GET http://localhost:5000/orders/1

####

GET http://localhost:5000/ordersByUser/1

###

GET http://localhost:5000/ordersByClient/1

###

GET http://localhost:5000/ordersLaundry

###


GET http://localhost:5000/ordersIron

###

GET http://localhost:5000/ordersSelfService

###

GET http://localhost:5000/ordersLaundry

###


POST http://localhost:5000/ordersMany
Content-Type: application/json



###
POST http://localhost:5000/orders
Content-Type: application/json

{
  
  "numberOfItems": 5,
    "receptionDate": "2023-10-11T00:00:00.000Z",
    "receptionTime": "1970-01-01T13:15:48.000Z",
    "scheduledDeliveryDate": "2023-10-14T00:00:00.000Z",
    "scheduledDeliveryTime": "1970-01-01T16:00:00.000Z",
    "payForm": "delivery",
    "payStatus": "unpaid",
    "orderStatus": "pending",
    "totalPrice": 35.28,
    "fk_client": 2,
    "fk_user": 3,
    "fk_categoryDescription":"encargo"
}

###
DELETE   http://localhost:5000/orders/1

###

DELETE   http://localhost:5000/ordersAll

###

//CRUD DE PAYMENT
GET http://localhost:5000/payments

###

GET http://localhost:5000/payments/1

###

POST http://localhost:5000/payments
Content-Type: application/json

{
  "fk_idOrder" :4,
  "payTotal"  :60,
  "payMethod" : "cash",
  "payDate" :   "2023-11-01T00:00:00.000Z",
  "payTime":"1970-01-01T16:00:00.000Z",
  "fk_cashCut": 2
}

###
PATCH  http://localhost:5000/payments/1
Content-Type: application/json

{
    "payMethod":"credit"
}
###
DELETE   http://localhost:5000/payments/19

###
//CRUD DE CASHCUT
GET http://localhost:5000/cashCuts

###

GET http://localhost:5000/cashCutStatus

###
GET http://localhost:5000/lastCashCut

###

GET http://localhost:5000/cashCuts/1

###
GET  http://localhost:5000/calculateCashCut/48

###

GET  http://localhost:5000/closeCashCut/7

###

POST http://localhost:5000/cashCuts
Content-Type: application/json

{
    "fk_user": 2,
    "cashCutD": "2023-10-08T00:00:00.000Z",
    "cashCutT": "1970-01-01T08:12:36.000Z"

}

###
PATCH  http://localhost:5000/cashCuts/1
Content-Type: application/json

{
    "subtotal":1500.50
}

###
DELETE http://localhost:5000/cashCuts/48

### 

//CRUD DE PAYMENTS
GET http://localhost:5000/payments

###

GET http://localhost:5000/payments/2

###
POST http://localhost:5000/payments
Content-Type: application/json

{
  "fk_idOrder":1,     
  "fk_userCashier":1,
  "payTotal": 500.30,
  "payMethod":"cash",      
  "payDate": "2023-11-11T00:00:00.000Z",         
  "payTime": "1970-01-01T12:20:20.000Z"       
  //"fk_cashCut":     

}

###


POST http://localhost:5000/paymentsAdvance
Content-Type: application/json

{
  "payment":{
    "fk_idOrder":39,     
  //"fk_userCashier":2,
  "payTotal": 300,
  "payMethod":"cash",     
  "payDate": "2023-11-11T00:00:00.000Z",         
  "payTime": "1970-01-01T12:20:20.000Z",       
  "fk_cashCut":23     

  }
  
}
###

POST http://localhost:5000/paymentsDelivery
Content-Type: application/json

{
  "payment":{
    "fk_idOrder":149,     
  //"fk_userCashier":2,
  "payTotal": 400,
  "payMethod":"cash",     
  "payDate": "2023-11-11T00:00:00.000Z",         
  "payTime": "1970-01-01T12:20:20.000Z",       
  "fk_cashCut":23     

  },
  "deliveryDetail":{
    "fk_idOrder":149,
    "fk_userCashier":3,
    "deliveryDate":"2023-11-11T00:00:00.000Z",
    "deliveryTime":"1970-01-01T12:20:20.000Z"
    
  }
  
}

###
PATCH  http://localhost:5000/payments/3
Content-Type: application/json

{
  "fk_idOrder":1,     
  "fk_userCashier":1,
  "payTotal": 14500.30,
  "payMethod":"cash",      
  "payDate": "2023-11-11T00:00:00.000Z",         
  "payTime": "1970-01-01T12:20:20.000Z"       
  //"fk_cashCut":     
}

###
DELETE http://localhost:5000/payments/7

### 

//CRUD DE DELIVERY DETAIL
GET http://localhost:5000/deliveryDetails

###

GET http://localhost:5000/deliveryDetails/2

###
POST http://localhost:5000/deliveryDetails
Content-Type: application/json

{
  "fk_userCashier": 1,
  "fk_idPayment":  1,  
  "deliveryDate":   "2023-11-15T00:00:00.000Z",
  "deliveryTime":   "1970-01-01T12:20:20.000Z"
}
   

###
PATCH  http://localhost:5000/deliveryDetails/1
Content-Type: application/json

{
       
  "deliveryTime":   "1970-01-01T13:20:20.000Z"   
       
}

###
DELETE http://localhost:5000/deliveryDetails/7

### 

//CRUD DE CASH WHITHDRAWALS

GET http://localhost:5000/cashWithdrawals

###

GET http://localhost:5000/cashWithdrawals/1

###

POST http://localhost:5000/cashWithdrawals
Content-Type: application/json

{
  "fk_cashCut" :2,
  "fk_user":2,
  "amount" : 300.00,
  "cause":"Pago renta",
  "date" :"2023-10-15T00:00:00.000Z"
}
###
PATCH  http://localhost:5000/cashWithdrawals/1
Content-Type: application/json

{
    "amount":400.00
}
###
DELETE   http://localhost:5000/cashWithdrawals/19


//CRUD DE IRON SERVICE DETAILS
GET http://localhost:5000/orderIronServiceDetails

###

GET http://localhost:5000/orderIronServiceDetails/20

###

POST http://localhost:5000/orderIronServiceDetails
Content-Type: application/json

{
  
    "fk_idOrderServiceDetail":20,
  
  "fk_idMachine":  1,
  "fk_staffMember": 1,
  "serviceDate":   "2023-10-15T00:00:00.000Z",
  "serviceTime":    "1970-01-01T16:00:00.000Z"

}

###
PATCH  http://localhost:5000/orderIronServiceDetails/1
Content-Type: application/json

{
    "finished":true
}
###
DELETE   http://localhost:5000/orderIronServiceDetails/17

###


//CRUD PRETTY CASH

POST http://localhost:5000/pettyCashWithdrawal 
Content-Type: application/json

{
    "amount": 100,
    "balance": 0,
    "movementDate": "2023-11-14T00:00:00.000Z",
    "cause": "Hialuronato de Sodio2",
    "fk_user" :2,
    "pettyCashType": "withdrawal"
  }

###
GET   http://localhost:5000/pettyCash
####

//QUEUE CRUDS
GET   http://localhost:5000/laundryQueue
###
//QUEUE CRUDS

GET   http://localhost:5000/selfServiceQueue
####

GET   http://localhost:5000/servicesIron
####

GET   http://localhost:5000/servicesSelfService